"""describe change

Revision ID: 1f03d156db7c
Revises: baa77db0f53f
Create Date: 2026-03-12 23:17:56.063217
"""


# revision identifiers, used by Alembic.
revision = '1f03d156db7c'
down_revision = 'baa77db0f53f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
