"""tea_session add teaware_id and change session_date to date

Revision ID: 5a98ed696749
Revises: 9c06c2103db7
Create Date: 2026-03-21 17:01:43.458006
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '5a98ed696749'
down_revision = '9c06c2103db7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tea_sessions', sa.Column('teaware_id', sa.Integer(), nullable=True))
    op.alter_column('tea_sessions', 'session_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='session_date::date')
    op.create_index(op.f('ix_tea_sessions_teaware_id'), 'tea_sessions', ['teaware_id'], unique=False)
    op.create_foreign_key(None, 'tea_sessions', 'teaware', ['teaware_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tea_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_tea_sessions_teaware_id'), table_name='tea_sessions')
    op.alter_column('tea_sessions', 'session_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('tea_sessions', 'teaware_id')
    # ### end Alembic commands ###
