"""changed tasting_session names

Revision ID: baa77db0f53f
Revises: cd76ba044650
Create Date: 2026-03-12 22:25:14.643271
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa77db0f53f'
down_revision = 'cd76ba044650'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasting_sessions', sa.Column('session_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasting_sessions', sa.Column('rating', sa.Integer(), nullable=True))
    op.drop_column('tasting_sessions', 'score')
    op.drop_column('tasting_sessions', 'brewed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasting_sessions', sa.Column('brewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tasting_sessions', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tasting_sessions', 'rating')
    op.drop_column('tasting_sessions', 'session_date')
    # ### end Alembic commands ###
