"""add brew params and steep infusions

Revision ID: bed53e75e2be
Revises: b3c4d5e6f7a8
Create Date: 2026-03-26 23:13:57.948402
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed53e75e2be'
down_revision = 'b3c4d5e6f7a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steep_infusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('steep_number', sa.Integer(), nullable=False),
    sa.Column('steep_time_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tea_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'steep_number')
    )
    op.create_index(op.f('ix_steep_infusions_session_id'), 'steep_infusions', ['session_id'], unique=False)
    op.add_column('tea_sessions', sa.Column('water_temp_c', sa.Float(), nullable=True))
    op.add_column('tea_sessions', sa.Column('leaf_weight_g', sa.Float(), nullable=True))
    op.add_column('tea_sessions', sa.Column('water_volume_ml', sa.Float(), nullable=True))
    op.add_column('tea_sessions', sa.Column('brew_method', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tea_sessions', 'brew_method')
    op.drop_column('tea_sessions', 'water_volume_ml')
    op.drop_column('tea_sessions', 'leaf_weight_g')
    op.drop_column('tea_sessions', 'water_temp_c')
    op.drop_index(op.f('ix_steep_infusions_session_id'), table_name='steep_infusions')
    op.drop_table('steep_infusions')
    # ### end Alembic commands ###
