"""add tasting session table

Revision ID: cd76ba044650
Revises:
Create Date: 2026-03-12 21:42:13.490033
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd76ba044650"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("vendor", sa.String(length=120), nullable=True),
        sa.Column("origin", sa.String(length=120), nullable=True),
        sa.Column("tea_type", sa.String(length=50), nullable=True),
        sa.Column("harvest_year", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teas_name"), "teas", ["name"], unique=False)
    op.create_table(
        "tasting_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tea_id", sa.Integer(), nullable=False),
        sa.Column("brewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tea_id"],
            ["teas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tasting_sessions_tea_id"), "tasting_sessions", ["tea_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasting_sessions_tea_id"), table_name="tasting_sessions")
    op.drop_table("tasting_sessions")
    op.drop_index(op.f("ix_teas_name"), table_name="teas")
    op.drop_table("teas")
    # ### end Alembic commands ###
